require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - bin/*
    - lib/tasks/*
    - spec/cypress/app_commands/log_fail.rb
    - config/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/SubjectStub:
  Exclude:
    - spec/controllers/application_controller_spec.rb
RSpec/NamedSubject:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false