exclude:
  - app/views/home/roadmap.html.slim
  - app/views/articles/show.html.slim
  - app/views/newsletter_mailer/newsletter.html.slim
  - app/views/chord_sheets/_chord_diagram_icon.html.slim

linters:
  LineLength:
    max: 135
    exclude:
      - app/views/devise/shared/_links.html.slim
      - app/views/home/privacy.html.slim
      - app/views/layouts/mailer.html.slim
      - app/views/devise/mailer/confirmation_instructions.html.slim
      - app/views/devise/mailer/reset_password_instructions.html.slim
      - app/views/devise/mailer/email_changed.html.slim
  TrailingWhitespace:
    exclude:
      - app/views/home/about.html.slim
      - app/views/home/privacy.html.slim
